---
galaxy_info:
  description: PHP for Ubuntu

  license: MIT

  min_ansible_version: 2.7

  platform:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - php
    - development
    - web
    - drupal

dependencies: []
