---

- name: Add NodeSource GPG key
  apt_key:
    data: "{{ lookup('file', 'nodesource.gpg.key') }}"

- name: Add NodeSource APT repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main'

- name: Ensure required packages are present
  package:
    name: 
      - libjpeg-turbo8
      - nodejs
    state: present

- name: Install gulp
  npm:
    name: gulp-cli
    global: yes

- name: Copy assets common
  synchronize:
    src: "{{ playbook_dir }}/../modules/ytp-assets-common/"
    dest: "{{ server_path }}/ytp-assets-common"
    rsync_opts:
    - "--exclude=node_modules"
    - "--exclude=src/vendor"
    - "--exclude=resources"

- name: Ensure www path is present
  file:
    path: "/var/www"
    state: directory
    mode: "0755"
    owner: root
    group: root

- include: vagrant.yml
  when: deployment_environment_id == "vagrant"

- include: nonvagrant.yml
  when: deployment_environment_id != "vagrant"

- name: Install resource dependencies
  command:  npm install --unsafe-perm=true --allow-root
  args:
    chdir: "{{ server_path }}/ytp-assets-common"

- name: Run gulp
  command: gulp
  args:
    chdir: "{{ server_path }}/ytp-assets-common"

- name: Copy resources
  shell: cp -R {{ server_path }}/ytp-assets-common/resources /var/www/resources

- include: pip.yml
