---

# Web modules

- name: Clear module cache
  file:
    path: "{{ cache_path }}/{{ item }}"
    state: absent
  with_items:
    - modules
  when: clear_module_cache
  tags:
  - common
  - clear-cache

- name: Clear module tar cache
  file:
    path: "{{ cache_path }}/{{ item }}.tar"
    state: absent
  with_items:
    - modules
  when: clear_module_cache
  tags:
  - common
  - clear-cache

- name: Package modules
  local_action: command tar -c --exclude=.git --exclude-from={{ item }}/.gitignore -f {{ item }}.tar {{ item }} chdir="{{ modules_path }}"
  become: false
  with_flattened:
    - "{{ modules }}"
  args:
    warn: false   # To quiet warnings about using tar as archive module does not suit for this purpose.
  tags:
  - common
  - ckan
  - drupal
  - resources
  - modules
  - translations
  - drupal-translations

- name: Copy modules
  copy:
    src: "{{ modules_path }}/{{ item }}.tar"
    dest: "{{ cache_path }}"
  register: modules_copy
  with_flattened:
    - "{{ modules }}"
  tags:
  - common
  - ckan
  - drupal
  - resources
  - modules
  - translations
  - drupal-translations

- name: Delete old modules
  file:
    path: "{{ cache_path }}/{{ item }}"
    state: absent
  when: modules_copy is changed
  with_flattened:
    - "{{ modules }}"
  tags:
  - common
  - ckan
  - drupal
  - resources
  - modules
  - translations

- name: Extract modules
  unarchive:
    src: "{{ cache_path }}/{{ item }}.tar"
    dest: "{{ cache_path }}"
  when: modules_copy is changed
  with_flattened:
    - "{{ modules }}"
  tags:
  - common
  - ckan
  - drupal
  - resources
  - modules
  - translations

# Web resources

- name: Ensure www path is present
  file:
    path: "/var/www"
    state: directory
    mode: "0755"
    owner: root
    group: root
  tags:
  - resources

- name: Clean resources
  file:
    path: /var/www/resources
    state: absent
  when: modules_copy is changed
  tags:
  - resources

- name: Install gulp
  npm:
    name: gulp-cli
    global: yes
  tags:
  - gulp

- name: Ensure resource dependencies path is present
  file:
    path: "{{ cache_path }}/resource-dependencies"
    state: directory
    mode: "0755"
    owner: root
    group: root
  when: modules_copy is changed
  tags:
  - resources

- name: Copy resource dependency base
  shell: cp -R {{ cache_path }}/ytp-assets-common/* {{ cache_path }}/resource-dependencies
  when: modules_copy is changed
  tags:
  - resources

- name: Install resource dependencies
  command:  npm install --unsafe-perm=true --allow-root
  args:
    chdir: "{{cache_path}}/resource-dependencies"
  when: modules_copy is changed

- name: Symlink avoindata drupal theme to cache folder
  file:
    state: link
    src: "{{ playbook_dir }}/../modules/avoindata-drupal-theme"
    dest: "{{ cache_path }}/avoindata-drupal-theme"
    force: yes
  tags:
  - drupal
  - gulp

- name: Run gulp
  command: gulp
  args:
    chdir: "{{ cache_path }}/resource-dependencies"
  tags:
  - gulp

- name: Copy resources
  shell: cp -R {{ cache_path }}/resource-dependencies/resources /var/www/resources
  when: modules_copy is changed
  tags:
  - resources

- include: pip.yml
