---

# Web resources

- name: Ensure www path is present
  file:
    path: "/var/www"
    state: directory
    mode: "0755"
    owner: root
    group: root
  tags:
  - resources

- name: Clean resources
  file:
    path: /var/www/resources
    state: absent
  tags:
  - resources


- include: vagrant.yml
  when: deployment_environment_id == "vagrant"


- include: nonvagrant.yml
  when: deployment_environment_id != "vagrant"

- include: pip.yml
