- name: Copy secret .npmrc
  copy:
    src: "/root/avoindata-secrets/{{ deployment_environment_id }}/.npmrc"
    dest: "{{server_path}}/ytp-assets-common/.npmrc"
  when: AWS.enabled == True

- name: Copy fallback package.json if npmrc does not exist
  copy:
    src: package.json
    dest: "{{ server_path }}/ytp-assets-common/package.json"
  when: AWS.enabled != True

- name: Synchronize avoindata drupal theme to cache folder
  synchronize:
    src: "{{ playbook_dir }}/../modules/avoindata-drupal-theme/"
    dest: "{{ server_path }}/avoindata-drupal-theme"

- name: Synchronize avoindata drupal header to cache folder
  synchronize:
    src: "{{ playbook_dir }}/../modules/avoindata-drupal-header/"
    dest: "{{ server_path }}/avoindata-drupal-header"

- name: Install resource dependencies
  command:  npm install --unsafe-perm=true --allow-root
  args:
    chdir: "{{ server_path }}/ytp-assets-common"