---
- name: Install virtualenv
  apt:
    package: virtualenv
    state: installed

- name: Upgrade pip packages
  pip:
    name:
      - pip
      - setuptools==36.1
      - boto
    virtualenv: "{{ virtual_environment }}"
    state: latest