AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  RegistryAddress:
    Type: 'AWS::SSM::Parameter::Value<String>'
  EnvironmentName:
    Type: 'AWS::SSM::Parameter::Value<String>'

Globals:
  Function:
    Timeout: 3

Resources:
  NewFileHandler:
    Type: AWS::Serverless::Function
    DependsOn: VirusScannerTaskDefinition
    Properties:
      CodeUri: new_file_handler/
      Handler: app.lambda_handler
      Environment:
        Variables:
          VPC_ID: !ImportValue vpc-VPC
      Runtime: python3.7
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
              Resource:
                - "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - !GetAtt VirusScannerRole.Arn
                - !GetAtt TaskExecutionRole.Arn
            - Effect: Allow
              Action:
                - ec2:DescribeSubnets
              Resource: "*"
              
  PermissionForS3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NewFileHandler
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::avoindata-${EnvironmentName}-datasets"
  
  ClamAvCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: clamav-scanner-cluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: clamav-s3-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: "*"

  VirusScannerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: clamav-scanner
          Image: !Sub "${RegistryAddress}:latest"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: fargate
              awslogs-stream-prefix: clamav-scanner
              awslogs-create-group: true
      Cpu: 2048
      ExecutionRoleArn: !Ref TaskExecutionRole
      Family: clamav-scanner
      Memory: 4096
      NetworkMode: awsvpc
      RequiresCompatibilities: 
        - FARGATE
      TaskRoleArn: !Ref VirusScannerRole

  VirusScannerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ecs-tasks.amazonaws.com
      Policies:
        - PolicyName: clamav-s3-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:DeleteObjectTagging
                  - s3:GetObject
                  - s3:GetObjectTagging
                  - s3:HeadBucket
                  - s3:ListObjects
                  - s3:PutObjectTagging
                Resource: 
                  - !Sub "arn:aws:s3:::avoindata-${EnvironmentName}-datasets"
                  - !Sub "arn:aws:s3:::avoindata-${EnvironmentName}-datasets/*"
  VirusScannerLambdaArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${EnvironmentName}/clamav/lambdaarn
      Type: "String"
      Value: !GetAtt NewFileHandler.Arn