vagrant: true
secrets_file_path: does_not_exist
deployment_environment_id: vagrant
ssl_path: /vagrant


www_root: /var/www
www_user: www-data
www_group: www-data

server_path: /srv/ytp
cache_path: "{{ server_path }}/cache"
backup_path: "{{ server_path }}/backup"
scripts_path: "{{ server_path }}/scripts"
log_path: /var/log/ckan
static_path: "{{ www_root }}/static"

resource_cache_path: "{{ server_path }}/resource_cache"

files_root: "{{ server_path }}/files"

all_paths:
  - "{{ server_path }}"
  - "{{ cache_path }}"
  - "{{ backup_path }}"
  - "{{ scripts_path }}"
  - "{{ log_path }}"
  - "{{ static_path }}"
