---
# tasks file for apache

- name: Ensure Apache is installed
  apt:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"

- name: Disable default Apache sites
  file:
    path: "/etc/apache2/sites-enabled/{{ item }}"
    state: absent
  with_items:
    - 000-default.conf
    - default-ssl.conf

- name: Create site configurations
  copy:
    content: "{{ item.config }}"
    dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
    mode: "0644"
    owner: root
    group: root
  with_items: "{{ apache_sites }}"

- name: Enable Apache2 modules
  apache2_module:
    name: "{{ item }}"
  with_items: "{{ apache_enabled_modules }}"

- name: Enable Apache configuration
  file:
    src: "/etc/apache2/sites-available/{{ item.name }}.conf"
    dest: /etc/apache2/sites-enabled/{{ item.name }}.conf
    state: link
    owner: root
    group: root
  with_items: "{{ apache_sites }}"
  notify: Restart Apache

- name: Create Apache port configuration
  copy:
    content: "{{ apache_port_config }}"
    dest: "/etc/apache2/ports.conf"
    mode: "0644"
    owner: root
    group: root
  when: apache_port_config is defined
  notify: Restart Apache

- name: Ensure Apache service state
  systemd:
    name: "{{ apache_service }}"
    state: "{{ apache_service_state }}"
    enabled: "{{ apache_service_enabled }}"

# Ensure apache settings (port changes) are applied immediately
- name: Force all notified handlers to run at this point
  meta: flush_handlers
