---
galaxy_info:
  description: Drupal for Ubuntu

  license: MIT

  min_ansible_version: 2.6

  platform:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - php
    - development
    - web
    - drupal

dependencies:
  - role: secrets
  - role: php
    tags: dependency_role
  - role: composer
    tags: dependency_role
  - role: opendata_frontend
    tags: dependency_role
  - role: postgres
    tags: dependency_role
  - role: nginx
    tags: dependency_role
