AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  DevAccountId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /build/accountid
    Description: 'ID of the account that should invoke the deployment'
Globals:
  Function:
    Timeout: 600

Resources:
  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS:
                !Sub 'arn:aws:iam::${DevAccountId}:role/InvokeDeploymentRole'
      RoleName: DeploymentRole
      Policies:
        - PolicyName: DeploymentPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/beta/web/amiid
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/beta/scheduled/amiid
