---
# tasks file for common
- name: Check submodule status
  delegate_to: localhost
  become: false
  shell: >
    git submodule status --recursive| egrep '^[+-]' -c
  args:
    chdir: "{{ playbook_dir }}"
  register: common_submodule_status
  failed_when: common_submodule_status.rc > 1
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Pause if currently checked out submodule commit does not match repo
  delegate_to: localhost
  become: false
  pause:
    prompt: "{{ common_submodule_status.stdout }} modules have changed, continue?"
  when:
    - common_submodule_status.stdout > "0"
    - not common_skip_submodule_check

- name: Copy apt sources.list
  template:
    src: "sources.list.j2"
    dest: "/etc/apt/sources.list"
    mode: "0644"
    owner: root
    group: root
    backup: true
  when: common_deployment_environment_id == "vagrant"

- name: Update packages
  apt:
    upgrade: "{{ common_apt_upgrade }}"
    update_cache: true

- name: Set locale
  lineinfile:
    path: "/etc/environment"
    line: "LC_ALL=en_US.utf8"
    regexp: "^LC_ALL=.*"

- name: Import configuration tasks
  import_tasks: configure.yml
  tags:
    - configure
