---
# tasks file for common
- name: Update packages
  apt:
    upgrade: dist
    update_cache: true

- name: Set hostname
  hostname:
    name: "{{ deployment_environment_id }}-web"

- name: Set locale
  lineinfile:
    path: "/etc/environment"
    line: "LC_ALL=en_US.utf8"
    regexp: "^LC_ALL=.*"

- name: Create common paths
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ all_paths }}"
