---

- name: Install Clamav packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - clamav
  register: clamav_install
  tags:
  - packages
  - clamav
  - non-local

# Removed when clause 'when: clamav_install|changed' due to Ansible bug https://github.com/ansible/ansible/issues/7432
- name: Update virus definition
  command: freshclam --quiet
  async: 7200
  poll: 0
  tags:
  - clamav
  - non-local

- name: Copy daily virus check
  template:
    src: "daily.j2"
    dest: "/etc/cron.daily/ytp_clamscan"
    mode: "0755"
    owner: root
    group: root
  tags:
  - clamav
  - non-local

- name: Copy hourly virus check
  template:
    src: "hourly.j2"
    dest: "/etc/cron.hourly/ytp_clamscan"
    mode: "0755"
    owner: root
    group: root
  tags:
  - clamav
  - non-local
