---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: xenialxerus
    box: bento/ubuntu-16.04
  - name: bionicbeaver
    box: bento/ubuntu-18.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      stdout_callback: yaml
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
