---
# defaults file for php

php_www_user: www-data
php_www_group: www-data

php_packages_state: present

php_required_packages:
  - php
  - php-fpm
  - php-gd
  - php-pgsql
  - php-xml  # installs "dom"
  - php-mbstring
  - php-curl
