---

- name: Ensure temp directory for extensions
  file:
    path: "{{ ckanext_sync_path }}"
    state: directory

- name: Ensure cache directory for pip
  file:
    path: /home/vagrant/.cache/pip/http
    state: directory
  when: deployment_environment_id == "vagrant"

- include: extension.yml
  with_items: "{{ ckan_extensions }}"

  #- name: Install spatial requirements
  #pip: requirements="{{ cache_path }}/ckanext-spatial/pip-requirements.txt" virtualenv="{{ virtual_environment }}"  extra_args='--exists-action=w --timeout=30'
  #tags:
  #- ckan
  #- spatial

#- name: Install googleanalytics requirements
#  pip: requirements="{{ cache_path }}/ckanext-googleanalytics/pip-requirements.txt" virtualenv="{{ virtual_environment }}" state=latest extra_args='--exists-action=w --timeout=30'
#  tags:
#  - ckan
#  - google-analytics

    #- name: Install archiver requirements
    #pip: requirements="{{ cache_path }}/ckanext-archiver/requirements.txt" virtualenv="{{ virtual_environment }}" state=latest extra_args='--exists-action=w --timeout=30'
    #tags:
    #- ckan
    #- qa
    #
    #- name: Install qa requirements
  #pip: requirements="{{ cache_path }}/ckanext-qa/requirements.txt" virtualenv="{{ virtual_environment }}" extra_args='--exists-action=w --timeout=30'
  #tags:
  #- ckan
  #- qa
  #
  #- name: Install dcat requirements
  #pip: requirements="{{ cache_path }}/ckanext-dcat/requirements.txt" virtualenv="{{ virtual_environment }}" extra_args='--exists-action=w --timeout=30'
  #tags:
  #- ckan
  #- dcat
  #
  #- name: Ensure SqlAlchemy version
  #pip: name="sqlalchemy" virtualenv="{{ virtual_environment }}" version="0.9.6" extra_args='--exists-action=w --upgrade --force-reinstall --timeout=30'
  #tags:
  #- ckan
  #- spatial
  #



- name: Copy credentials token
  copy:
    src: "{{ google_credentials }}"
    dest: "{{ cache_path }}/token.dat"
    mode: "0644"
    owner: root
    group: "{{ www_group }}"
  when: google_analytics != false
  tags:
    - ckan
    - google-analytics

- name: Add analytics fetching to cron
  cron:
    name: "analytics"
    minute: "*/5"
    hour: "0-3"
    job: "{{ virtual_environment }}/bin/paster --plugin=ckanext-googleanalytics googleanalytics loadanalytics {{cache_path}}/token.dat --config={{ ckan_ini }}"
  when: google_analytics != false
  tags:
    - ckan
    - google-analytics
