version: 2
jobs:
  run-flake8:
    docker:
      - image: circleci/python:2.7.15

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "codestyle-requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install codestyle requirements
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r codestyle-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "codestyle-requirements.txt" }}

      - run:
          name: run linting
          command: |
            . venv/bin/activate
            flake8 modules --max-line-length=140

  run-code-sniffer:
    docker:
      - image: circleci/php:7.1

    steps:
      - checkout

      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev libpng-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install gd

      # composer cache
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "drupal8/composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          command: composer install -n --prefer-dist
          working_directory: ~/project/drupal8/

      - run:
          name: Run codesniffer for drupal standard
          command: ./vendor/bin/phpcs --standard=Drupal ../modules --ignore=ckanext*
          working_directory: ~/project/drupal8/

      - run:
          name: Run codesniffer for drupal practice
          command: ./vendor/bin/phpcs --standard=DrupalPractice ../modules --ignore=ckanext*
          working_directory: ~/project/drupal8/

      - save_cache:
          key: composer-v1-{{ checksum "drupal8/composer.json" }}
          paths:
            - vendor
      - run: sudo pip install ansible-lint

  run-ansible-lint:
    docker:
      - image: circleci/python

    steps:
      - checkout

      - run: sudo pip install ansible-lint

      - run:
          name: Run ansible-lint for single-server.yml
          command: ansible-lint single-server.yml
          working_directory: ~/project/ansible/

workflows:
  version: 2
  lint-all:
    jobs:
      - run-flake8
      - run-code-sniffer
      - run-ansible-lint
