version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "codestyle-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install flake8
          command: |
            python2 -m venv env
            . env/bin/activate
            pip install -r codestyle-requirements.txt

      - save_cache:
        paths:
          - ./venv
          key: v1-dependencies-{{ checksum "codestyle-requirements.txt" }}

      - run:
        name: run linting and metrics
          command: |
            . venv/bin/activate
            flake8 modules --output-file test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
