version: 2
jobs:
  run-flake8:
    docker:
      - image: circleci/python:2.7.15

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "codestyle-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install codestyle requirements
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r codestyle-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "codestyle-requirements.txt" }}

      - run:
          name: run linting
          command: |
            . venv/bin/activate
            flake8 modules --max-line-length=140

  run-ansible-lint:
    docker:
      - image: circleci/python

    steps:
      - checkout

      - run: sudo pip install ansible-lint

      - run:
          name: Run ansible-lint for single-server.yml
          command: ansible-lint single-server.yml
          working_directory: ~/project/ansible/

workflows:
  version: 2
  lint-all:
    jobs:
      - run-flake8
      - run-ansible-lint
