version: 2
jobs:
  lint_python:
    docker:
      - image: circleci/python:2.7.15

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "codestyle-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install codestyle requirements
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r codestyle-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "codestyle-requirements.txt" }}

      - run:
          name: run linting
          command: |
            . venv/bin/activate
            flake8 modules --output-file test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
workflows:
  version: 2
  lint_all:
    jobs:
      - lint_python