version: 2
jobs:
  run-flake8:
    docker:
      - image: circleci/python:2.7.15

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "codestyle-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install codestyle requirements
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r codestyle-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "codestyle-requirements.txt" }}

      - run:
          name: run linting
          command: |
            . venv/bin/activate
            flake8 modules --max-line-length=140

  run-code-sniffer:
    docker:
      - image: juampynr/drupal8ci:latest
    steps:
      - checkout

      - run:
          name: Build Drupal skeleton with Composer Drupal Project
          command: |
            composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction

workflows:
  version: 2
  lint-all:
    jobs:
      - run-flake8
      - run-code-sniffer