---
# tasks file for secrets

- name: Ensure secrets path exists
  file:
    path: "{{ secrets_destination_path }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  when: secrets_bucket != "does_not_exist"

- name: Copy secrets from S3 bucket
  aws_s3:
    bucket: "{{ secrets_bucket }}"
    object: "{{ item }}"
    dest: "{{ secrets_destination_path }}/"
    mode: get
  with_items: "{{ secrets_bucket_files }}"
  when: secrets_bucket != "does_not_exist"

- name: Include secrets from filesystem
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ secrets_file_path }}"
      skip: true
  no_log: true
