---
- name: Converge
  hosts: all
  become: true
  vars:
    apache_hostname: "localhost"
    apache_secondary_hostname: "127.0.0.1"
    apache_deployment_environment_id: molecule
  roles:
    - role: apache
