---

custom_modules:
  - { src_name: avoindata-drupal-header, module_name: avoindata-header }
  - { src_name: avoindata-drupal-hero, module_name: avoindata-hero }


# drupal_theme_path: "{{ drupal_root }}/sites/all/themes"
# features_module_path: "{{ drupal_root }}/sites/all/modules/ytp_features"

# bootstrap_version: "3.3.4"

# drupal_files_path: "{{ files_root }}/drupal"

# extracted_features:
#   - language_feature
#   - article_feature
#   - service_alert_feature
#   - article_view_feature
#   - blocks_feature
#   - frontpage_tutorial
#   - calendar_feature
#   - guide_feature
#   - frontpage_categories

# ytp_features_path: "../modules/ytp-drupal-features"

# translation_cache_path: "{{ cache_path }}/translations"
# translation_languages:
#   - "fi"
#   - "sv"
# translation_projects:
#   - "ytp-theme-drupal"
#   - name: "ckanext-ytp_main"
#     path: "/ckanext/ytp"
#   - "ytp-drupal-tutorial"
#   - "ytp-drupal-frontpage"
# translation_text_groups:
#   - "field"
#   - "node"
#   - "blocks"

# enable_email_verification: False
# drupal_error_level: "2"
