---

custom_modules:
  - { src_name: avoindata-drupal-header, module_name: avoindata-header, machine_name: avoindata_header }
  - { src_name: avoindata-drupal-servicemessage, module_name: avoindata-servicemessage, machine_name: avoindata_servicemessage }
  - { src_name: avoindata-drupal-hero, module_name: avoindata-hero, machine_name: avoindata_hero }
  - { src_name: avoindata-drupal-categories, module_name: avoindata-categories, machine_name: avoindata_categories }
  - { src_name: avoindata-drupal-infobox, module_name: avoindata-infobox, machine_name: avoindata_infobox }
  - { src_name: avoindata-drupal-datasetlist, module_name: avoindata-datasetlist, machine_name: avoindata_datasetlist }
  - { src_name: avoindata-drupal-newsfeed, module_name: avoindata-newsfeed, machine_name: avoindata_newsfeed }
  - { src_name: avoindata-drupal-appfeed, module_name: avoindata-appfeed, machine_name: avoindata_appfeed }
  - { src_name: avoindata-drupal-footer, module_name: avoindata-footer, machine_name: avoindata_footer }
  - { src_name: avoindata-drupal-articles, module_name: avoindata-articles, machine_name: avoindata_articles }
  - { src_name: avoindata-drupal-events, module_name: avoindata-events, machine_name: avoindata_events }
  - { src_name: avoindata-drupal-guide, module_name: avoindata-guide, machine_name: avoindata_guide }
  - { src_name: avoindata-drupal-user, module_name: avoindata-user, machine_name: avoindata_user }

removed_extensions:
  - search
  - contextual
