---

- name: Create patch cache path
  file:
    path: "{{ patches_cache_path }}"
    state: directory
  tags:
  - ckan
  - patch_ckan

#- name: Fetch CKAN patches
#  get_url: url="{{ item.patch }}" dest="{{ patches_cache_path }}/{{ item.file }}"
#  register: fetch_patches
#  with_items: "{{ ckan_patches }}"
#  tags:
#  - ckan
#  - patch_ckan

- name: Apply CKAN patches
  patch:
    src: patches/{{ item.file }}.patch
    basedir: "{{ ckan_source_path }}"
    strip: 1
  with_items: "{{ new_ckan_patches }}"
  tags:
  - patch_ckan
  - ckan
