---
- name: Install polib
  pip:
    name: polib
    virtualenv: "{{ ckan_virtual_environment }}"
    state: latest
  tags:
    - skip_ansible_lint

- name: Compile extension translations
  command: "{{ ckan_virtual_environment }}/bin/python setup.py compile_catalog -f"
  with_items: "{{ ckan_extensions_with_translations }}"
  args:
    chdir: "{{ ckan_extension_sync_path }}/{{ item }}"
  tags:
    - skip_ansible_lint
