---
# tasks file for postgres

- name: Get distribution based variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Install python-psycopg2
  apt:
    name: python-psycopg2

- include: local.yml
  when: postgres_installed_locally

- include: rds.yml
  when: not postgres_installed_locally
