---

- name: Install postgres client
  apt:
    pkg: postgresql-client
    state: present

- name: Setup postgres users
  postgresql_user:
    db: postgres
    user: "{{ item.username }}"
    password: "{{ item.password }}"
    no_password_changes: true
    login_host: "{{ postgres_host }}"
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ postgres_admin_password }}"
  with_items: "{{ postgres_users }}"
  no_log: true

- name: Grant privileges to admin user
  postgresql_privs:
    db: postgres
    roles: "{{ postgres_admin_user }}"
    type: group
    objs: "{{ item.username }}"
    login_host: "{{ postgres_host }}"
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ postgres_admin_password }}"
  with_items: "{{ postgres_users }}"
  no_log: true

- name: Setup postgres databases
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    login_host: "{{ postgres_host }}"
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ postgres_admin_password }}"
  with_items: "{{ postgres_databases }}"

- name: Initialize Spatial database
  command: psql -f {{ role_path }}/files/enable-rds-postgis.sql --set ON_ERROR_STOP=1
  ignore_errors: true
  environment:
    PGHOST: "{{ postgres_host }}"
    PGDATABASE: "{{ item.name }}"
    PGUSER: "{{ postgres_admin_user }}"
    PGPASSWORD: "{{ postgres_admin_password }}"
  with_items: "{{ postgres_spatial_databases }}"
  tags:
    - skip_ansible_lint
