---

modules:
  - ytp-assets-common
  - ckanext-drupal7
  - ckanext-ytp_drupal
  - ckanext-ytp_tasks
  - ckanext-ytp_request
  - ckanext-ytp_main
  - ckanext-hierarchy
  - ckanext-googleanalytics
  - ckanext-ytp_comments
  - ytp-theme-drupal
  - ytp-drupal-user
  - ytp-drupal-tutorial
  - ytp-drupal-footer
  - ytp-drupal-frontpage
  - ckanext-qa
  - ckanext-archiver
  - ckanext-harvest
  - ckanext-spatial
  - ckanext-report
  - ckanext-datarequests
  - ckanext-dcat
  - ckanext-cloudstorage
  - ckanext-scheming
  - ckanext-fluent


modules_path: ../modules

clear_module_cache: false
