vagrant: true
secrets_file_path: does_not_exist
deployment_environment_id: vagrant
ssl_path: /vagrant
disqus_name: "localhost-avoindata-fi"

debug_enabled: true
smtp:
  server_domain: localhost




solr_port: "8983"

redis_hostname: "{{ database_host }}"
redis_port: "6379"


ckan_test_database: { 'name': "ckan_test", 'username': "{{ ckan_database_username }}" }



fqdn: vagrant.avoindata.fi
fqdn_language: fi
secondary_fqdn: vagrant.opendata.fi
secondary_fqdn_language: en
domain: ""
secondary_domain: ""



admin: {'username' : 'admin', 'password': 'admin', 'email': 'vagrant@localhost'}

harvest_user: {'username' : 'harvest', 'password': 'harvest', 'email': 'harvest@localhost'}

ytp_users:
  - username: 'test-editor'
    password: 'test-editor'
    email: 'editor@localhost'
  - username: 'test-publisher'
    password: 'test-publisher'
    email: 'publisher@localhost'
  - username: 'test-user'
    password: 'test-user'
    email: 'user@localhost'



email_domain: "{{ fqdn }}"
email_from: "no-reply@{{ email_domain }}"
error_email_from: "error@{{ email_domain }}"

admin_email: vagrant@localhost
error_email: "{{ admin_email }}"
client_email: vagrant@localhost

#smtp_server key is required by the external ckan mailer component
smtp_server_domain: "{{ smtp.server_domain }}"

google_analytics: false
# enable: google_analytics: { 'id': "", 'account': "", 'username': "", 'password': "", 'type': "" }
certificates_path: "/etc/ssl/opendata"

basic_auth_path: false
nfs_shared_path: "/srv/ytp/shared"
local_cache: "/tmp/ytp/cache"

import_base_organizations: false
import_finto_tags: false

recaptcha_public_key: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
recaptcha_private_key: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"

Reindex: false

show_postit_demo: true


secret:
  database_ckan_password: pass
  database_ckan_datastore_password: pass
  database_drupal_password: pass
  database_drupal8_password: pass
  drupal_hash_salt: IzqME5cJk_x1ZV7oO3UXtHnM7p8R-mLVU5ZiKPWbzDQ
  smtp_user: username
  smtp_password: password

rds_domain_common_part: cnb7uthj3tqq.eu-west-1.rds.amazonaws.com


AWS:
  enabled: false
  region: S3_EU_WEST
  use_iam_role: false
  access_key: somekey
  secret_access_key: somesecret
  ckan_s3_bucket: somebucket
  smtp_server_domain: "email-smtp.eu-west-1.amazonaws.com"
