postgres:
  users:
    ckan:
      username: ckan_default
      password: "{{ secret.database_ckan_password }}"
    ckan_datastore:
      username: datastore_default
      password: "{{ secret.database_ckan_datastore_password }}"
    drupal:
      username: drupal
      password: "{{ secret.database_drupal_password }}"
    drupal8:
      username: drupal8
      password: "{{ secret.database_drupal8_password }}"

  server:
    installed_locally: "{{ postgres_conf.installed_locally }}"
    host: "{{ postgres_conf.host }}"
    port: 5432
    admin_user: "{{ postgres_conf.admin_user }}"
    admin_password: "{{ postgres_conf.admin_password }}"
    trusted_ip_range: 10.0.0.0/8
  databases:
    ckan:
      name: ckan_default
      owner: ckan_default
    ckan_datastore:
      name: datastore_default
      owner: ckan_default
    drupal:
      name: drupal
      owner: drupal
    drupal8:
          name: drupal8
          owner: drupal8

postgres_conf:
  installed_locally: true
  host: 127.0.0.1
  admin_user: postgres
  admin_password:
