---
ckan_profiling_enabled: true
ckan_smtp_use_tls: False
ckan_smtp_port: 1025
ckan_site_protocol: "http"
ckan_disqus_name: "{{ disqus_name }}"
ckan_enable_cloudstorage: false
ckan_postgres_installed_locally: true
ckan_debug_enabled: true
ckan_deployment_environment_id: 'vagrant'

ckan_testing_ports:
  - 9090