---
postgres_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
  - {type: host, database: ckan_default, user: ckan_default, address: "{{ postgres_trusted_ip_range }}", auth_method: md5}
  - {type: host, database: datastore_default, user: ckan_default, address: "{{ postgres_trusted_ip_range }}", auth_method: md5}
  - {type: host, database: datastore_default, user: datastore_default, address: "{{ postgres_trusted_ip_range }}", auth_method: md5}
  - {type: host, database: drupal8, user: drupal8, address: "{{ postgres_trusted_ip_range }}", auth_method: md5}
  - {type: host, database: ckan_test, user: ckan_test, address: "{{ postgres_trusted_ip_range }}", auth_method: md5}

postgres_installed_locally: true
