---

- name: Create cache paths
  file:
    path: "{{ cache_path }}"
    state: directory
  tags:
  - firewall

- name: Copy firewall script
  template:
    src: "firewall.sh.j2"
    dest: "{{ cache_path }}/firewall.sh"
    mode: "0755"
    owner: root
    group: root
  register: firewall_script
  tags:
  - firewall

- name: Enable firewall
  command: "{{ cache_path }}/firewall.sh"
  when: firewall_script is changed
  tags:
  - firewall
