TODO: tämä tiedosto. alla oleva on vain referenssiksi.

front_page_introduction:
  title: 'Avoindata.fi'
  subtitle: 'DEV'
  introduction: 'Demoversio avoimen datan tieto- ja jakelukanavasta suomalaisille yhteisöille, yrityksille ja kansalaisille.'
  link_url: 'https://jotain'
  link_text: 'Lue lisää >>'