---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: xenialxerus
    box: bento/ubuntu-16.04
    memory: 2048
  - name: bionicbeaver
    box: bento/ubuntu-18.04
    memory: 2048
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      stdout_callback: yaml
      callback_whitelist: profile_roles,profile_tasks
scenario:
  name: default
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
