---

- name: Ensure nginx is installed
  apt:
    pkg: "nginx"
    state: latest
  tags:
    - nginx
    - packages

- name: Generate basic auth file
  template:
    src: "htpasswd.j2"
    dest: "{{ basic_auth_path }}"
    mode: "0640"
    owner: root
    group: "{{ www_group }}"
  when: basic_auth_path != false
  tags:
    - nginx

- name: Copy base Nginx configuration
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: "0644"
    owner: root
    group: root
  notify: Restart Nginx
  tags:
    - nginx

- name: Copy fastcgi_params configuration file
  template:
    src: "fastcgi_params.j2"
    dest: "/etc/nginx/fastcgi_params"
    mode: "0644"
    owner: root
    group: root
  notify: Restart Nginx
  tags:
    - nginx

- name: Copy Nginx sites
  template:
    src: "{{ item.template }}"
    dest: "/etc/nginx/{{ item.destination }}"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - { 'template':'nginx_site_config.j2','destination':'sites-available/ytp', 'server_name': "{{ hostname }}", 'snippet': 'ytp.conf', 'base_hostname': "{{ base_hostname }}" }
    - { 'template':'nginx_site_config.j2','destination':'sites-available/ytp-secondary', 'server_name': "{{ secondary_hostname }}", 'snippet': 'ytp-secondary.conf', 'base_hostname': "{{ secondary_base_hostname }}" }
    - { 'template':'nginx_redirect_sites.config.j2','destination':'sites-available/redirects'}
  notify: Restart Nginx
  tags:
    - nginx

- name: Copy snippets files
  template:
    src: "{{ item.template }}"
    dest: "/etc/nginx/snippets/{{ item.destination }}"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - { 'template':'server.config.j2', 'destination':'ytp.conf', 'root_redirect': "{{ hostname_language }}" }
    - { 'template':'server.config.j2', 'destination':'ytp-secondary.conf', 'root_redirect': "{{ secondary_hostname_language }}" }
    - { 'template':'nginx_security_headers.conf.j2', 'destination':'nginx_security_headers.conf', 'root_redirect': "{{ secondary_hostname_language }}" }
  notify: Restart Nginx
  tags:
    - nginx

- name: Enable Nginx site
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  with_items:
    - "ytp"
    - "ytp-secondary"
    - "redirects"
  tags:
    - nginx
  notify: Restart Nginx

- include: maintenance-start.yml
