---

- hosts: webserver
  become: true
  vars:
    database_host: "10.10.10.20"
    solr_host: "10.10.10.20"
    database_ip_range: "10.0.0.0/8"
    hostname: "10.10.10.10"
  vars_files:
    - "vars/common.yml"
    - ["{{ secrets_file_path }}", "vars/none.yml"]
    - ["vars/local.yml", "vars/none.yml"]
  roles:
    - common
    - firewall
    - users
    - clean
    - common_webserver
    - ssl
    - nfs_client
    - nginx
    - postfix
    - ckan-extensions
    - ckan
    - ckan-config
    - ckan-database
    - ckan-data
    - ckan-restart
    - drupal
    - data
    - datapusher
  handlers:
    - name: restart sshd
      service: name=ssh state=restarted
