---

# NOTE: Database server on beta does not have a firewall as it is
#       running on an isolated security group

- hosts: dbserver
  become: true
  vars:
    database_host: "127.0.0.1"
    solr_host: "127.0.0.1"
    database_ip_range: "10.0.0.0/8"
    hostname: "10.10.10.20"
    postgres:
      server:
        installed_locally: true
  vars_files:
    - "vars/common.yml"
    - ["{{ secrets_file_path }}", "vars/none.yml"]
    - ["vars/local.yml", "vars/none.yml"]
  roles:
    - common
    - users
    - clean
    - database
    - jetty
    - redis
    - nfs_server
    - postfix
    - clamav
  handlers:
    - name: restart sshd
      service: name=ssh state=restarted
