---

# Note! Setting environment variable
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# before running the playbook is necessary on macOS High Sierra and later

- name: This playbook configures opendata web stack using AWS cloudformation
  hosts: "localhost"
  connection: "local"
  gather_facts: no
  environment:
    AWS_PROFILE: "{{ aws_profile }}"

  tasks:
  - name: Configure web stack
    cloudformation:
      stack_name: "{{ lookup('aws_ssm', '/{{ deployment_environment_id }}/web/name', aws_profile=aws_profile ) }}"
      state: "{{ lookup('aws_ssm', '/{{ deployment_environment_id }}/web/status', aws_profile=aws_profile ) }}"
      region: "{{ lookup('aws_ssm', '/{{ deployment_environment_id }}/web/region', aws_profile=aws_profile ) }}"
      create_changeset: "{{ lookup('aws_ssm', '/{{ deployment_environment_id }}/web/changeset', aws_profile=aws_profile ) }}"
      template: ../cloudformation/instances.yml
      template_parameters:
        DatabaseSecurityGroup: "/{{ deployment_environment_id }}/web/database_security_group"
        EFSFileSystem: "/{{ deployment_environment_id }}/web/efs_file_system"
        EFSSecurityGroup: "/{{ deployment_environment_id }}/web/efs_security_group"
        EnvironmentName: "/{{ deployment_environment_id }}/web/environment_name"
        GitBranch: "/{{ deployment_environment_id }}/web/git_branch"
        HostedZoneId: "/{{ deployment_environment_id }}/web/hosted_zone_id"
        HostedZoneIdAlternate: "/{{ deployment_environment_id }}/web/hosted_zone_id_alternate"
        InstanceType: "/{{ deployment_environment_id }}/web/instance_type"
        NumberOfSubnets: "/{{ deployment_environment_id }}/web/number_of_subnets"
        PublicALBCertificate: "/{{ deployment_environment_id }}/web/public_alb_certificate"
        PublicALBCertificate2: "/{{ deployment_environment_id }}/web/public_alb_certificate2"
        PublicALBCertificate3: "/{{ deployment_environment_id }}/web/public_alb_certificate3"
        PublicALBCertificate4: "/{{ deployment_environment_id }}/web/public_alb_certificate4"
        PublicALBSubnets: "/{{ deployment_environment_id }}/web/public_alb_subnets"
        PrivateSubnets: "/{{ deployment_environment_id }}/web/private_subnets"
        Vpc: "/{{ deployment_environment_id }}/web/vpc"
        WhitelistedIpAddressHEL: "/{{ deployment_environment_id }}/web/white_listed_ip_address_hel"
        WhitelistedIpAddressTRE: "/{{ deployment_environment_id }}/web/white_listed_ip_address_tre"
