---

# This playbook installs all roles on a single server

- hosts: all
  become: true

  pre_tasks:
    - import_role:
        name: secrets
      tags: always

  roles:
    - role: common
      tags: common
    - role: solr
      tags: solr
    - role: redis
      tags: redis
    - role: apache
      tags: apache
    - role: ckan
      tags: ckan
    - role: datapusher
      tags: datapusher
    - role: dynatrace
      tags: dynatrace

  post_tasks:
    - import_role:
        name: cloudwatch_agent
      when: cloudwatch_agent_enabled
      tags: cloudwatch_agent_role
