---

# This playbook installs all roles on a single server

- hosts: localhost
  become: true

  pre_tasks:
    - name: Ensure www directory exists
      file:
        path: "/var/www"
        state: directory

    - name: Enable maintenance mode
      file:
        path: "/var/www/maintenance"
        state: touch

    - import_role:
        name: mailhog
      when: deployment_environment_id == 'vagrant'
      tags: mailhog_role

    - import_role:
        name: cloudwatch_agent
      when: AWS.enabled
      tags: cloudwatch_agent_role

  roles:
    - {role: common, tags: common_role}
    - {role: ckan, tags: ckan_role}
    - {role: drupal, tags: drupal_role}
    - {role: datapusher, tags: datapusher_role}

  post_tasks:
    - name: Remove maintenance mode
      file:
        path: "/var/www/maintenance"
        state: absent
