---

# This playbook installs all roles on a single server

- hosts: mainserver
  become: true
  vars:
    database_host: "127.0.0.1"
    solr_host: "127.0.0.1"
    database_ip_range: "127.0.0.1/8"

  pre_tasks:
    - import_role:
        name: mailhog
      when: vagrant is defined
      tags: mailhog_role
    - import_role:
        name: cloudwatch_agent
      when: AWS.enabled
      tags: cloudwatch_agent_role
  roles:
    - common
    - firewall
    - users
    - clean
    - database
    - common_webserver
    - nginx
    - jetty
    - redis
    - ckan-extensions
    - ckan
    - ckan-config
    - ckan-database
    - ckan-data
    - ckan-restart
    - drupal
    - clamav
    - data
    - datapusher
