---

# This playbook installs all roles on a single server

- hosts: mainserver
  become: true
  vars:
    database_host: "127.0.0.1"
    solr_host: "127.0.0.1"
    database_ip_range: "127.0.0.1/8"
  vars_files:
    - "vars/common.yml"
    - ["vars/environment-specific/{{ deployment_environment_id }}.yml", "vars/none.yml"]
    - ["{{ secrets_file_path }}", "vars/none.yml"]
    - ["vars/local.yml", "vars/none.yml"]

  tasks:
    - import_role:
        name: mailhog
      when: vagrant is defined
      tags: mailhog_role
  roles:
    - common
    - firewall
    - users
    - clean
    - database
    - common_webserver
    - ssl
    - nginx
    - jetty
    - redis
    - ckan-extensions
    - ckan
    - ckan-config
    - ckan-database
    - ckan-data
    - ckan-restart
    - drupal
    - clamav
    - data
    - datapusher
