---

# This playbook installs all roles on a single server

- hosts: localhost
  become: true
  vars:
    database_host: "127.0.0.1"
    solr_host: "127.0.0.1"
    database_ip_range: "127.0.0.1/8"

  pre_tasks:
    - name: Ensure www directory exists
      file:
        path: "/var/www"
        state: directory
        
    - name: Enable maintenance mode
      file:
        path: "/var/www/maintenance"
        state: touch

    - import_role:
        name: mailhog
      when: vagrant is defined
      tags: mailhog_role

    - import_role:
        name: cloudwatch_agent
      when: AWS.enabled
      tags: cloudwatch_agent_role

  roles:
    - common
    - database
    - opendata_frontend
    - nginx
    - jetty
    - redis
    - ckan-extensions
    - ckan
    - ckan-config
    - ckan-database
    - ckan-data
    - ckan-restart
    - drupal
    - data
    - datapusher

  post_tasks:
    - name: Remove maintenance mode
      file:
        path: "/var/www/maintenance"
        state: absent
