---

# This playbook installs all roles on a single server

- hosts: localhost
  become: true
  vars:
    database_host: "127.0.0.1"
    solr_host: "127.0.0.1"
    database_ip_range: "127.0.0.1/8"

  pre_tasks:
    - name: Ensure www directory exists
      file:
        path: "/var/www"
        state: directory

    - name: Enable maintenance mode
      file:
        path: "/var/www/maintenance"
        state: touch

    - import_role:
        name: mailhog
      when: vagrant is defined
      tags: mailhog_role

    - import_role:
        name: cloudwatch_agent
      when: AWS.enabled
      tags: cloudwatch_agent_role

  roles:
    - {role: common, tags: common_role}
    - {role: database, tags: database_role}
    - {role: opendata_frontend, tags: opendata_frontend_role}
    - {role: nginx, tags: nginx_role}
    - {role: jetty, tags: jetty_role}
    - {role: redis, tags: redis_role}
    - ckan-extensions
    - {role: ckan, tags: ckan_role}
    - ckan-config
    - ckan-database
    - ckan-data
    - ckan-restart
    - {role: drupal, tags: drupal_role}
    - {role: data, tags: data_role}
    - {role: datapusher, tags: datapusher_role}

  post_tasks:
    - name: Remove maintenance mode
      file:
        path: "/var/www/maintenance"
        state: absent
