---
- name: Create solr configuration file
  template:
    src: solr.xml.j2
    dest: /etc/solr/solr.xml
    mode: 0644
    owner: root
    group: root
  notify: Restart jetty

- name: Copy Solr schema
  template:
    src: schema.xml.j2
    dest: /etc/solr/conf/schema.xml
    mode: "0644"
    owner: root
    group: root
  notify: Restart jetty

- name: Setup Jetty8
  template:
    src: "jetty.j2"
    dest: "/etc/default/jetty8"
    mode: "0644"
    owner: root
    group: root
  register: jetty_setup
  notify: Restart jetty
  when:
    - ansible_distribution ==  "Ubuntu"
    - ansible_distribution_major_version == "16"

- name: Configure Jetty9
  lineinfile:
    dest: "/etc/jetty9/start.ini"
    regexp: "^#?jetty\\.port.+$"
    line: "jetty.port={{ solr_port }}"
    state: "present"
  notify: Restart jetty
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "18"

# Workaround for Ubuntu 18.04 where jetty9 does not observe solr by default:
# https://github.com/ckan/ckan/issues/4311
- name: Symlink solr-jetty.xml to webapps
  file:
    src: /etc/solr/solr-jetty.xml
    dest: /var/lib/jetty9/webapps/solr.xml
    state: link
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "18"

- name: Ensure Jetty is running
  service:
    name: "{{ solr_jetty_service }}"
    state: started
    enabled: true

- name: Force all notified handlers to run at this point
  meta: flush_handlers
