---

# THESE VARS ARE PUBLIC, DO NOT PUT SECRETS HERE

smtp:
  server_domain: email-smtp.eu-west-1.amazonaws.com

deployment_environment_id: beta
secrets_file_path: "../../avoindata-secrets/beta/secrets.yml"
disqus_name: "beta-avoindata-fi"
ansible_python_interpreter: "{{ ansible_playbook_python }}"
aws_profile: opendata

profiling_enabled: true

postgres_host: "{{ postgres_conf.host }}"
postgres_admin_user: "{{ postgres_conf.admin_user }}"
postgres_admin_password: "{{ postgres_conf.admin_password }}"

postgres_users:
  - username: ckan_default
    password: "{{ secret.database_ckan_password }}"
  - username: datastore_default
    password: "{{ secret.database_ckan_datastore_password }}"
  - username: drupal8
    password: "{{ secret.database_drupal8_password }}"
