---

# THESE VARS ARE PUBLIC, DO NOT PUT SECRETS HERE
smtp:
  server_domain: localhost

hostname: "{{ inventory_hostname }}"

vagrant: false
secrets_file_path: does_not_exist
deployment_environment_id: build_test
disqus_name: ""
ssl_path: /etc/ssl
database_host: "127.0.0.1"
solr_host: "127.0.0.1"
database_ip_range: "127.0.0.1/8"
