---

# THESE VARS ARE PUBLIC, DO NOT PUT SECRETS HERE
smtp:
  server_domain: localhost

hostname: "{{ inventory_hostname }}"

vagrant: false
secrets_file_path: does_not_exist
deployment_environment_id: build_test
disqus_name: ""
database_host: "127.0.0.1"
solr_host: "127.0.0.1"
database_ip_range: "127.0.0.1/8"

postgres_installed_locally: true

ckan_profiling_enabled: False
ckan_smtp_use_tls: False
ckan_smtp_port: 1025
ckan_site_protocol: "http"
ckan_disqus_name: "{{ disqus_name }}"
ckan_enable_cloudstorage: false
ckan_postgres_installed_locally: true

nginx_development_environment: true
