---

# THESE VARS ARE PUBLIC, DO NOT PUT SECRETS HERE

smtp:
  server_domain: email-smtp.eu-west-1.amazonaws.com

deployment_environment_id: prod
secrets_file_path: "../../avoindata-secrets/prod/secrets.yml"
disqus_name: "avoindatafi"
ansible_python_interpreter: "{{ ansible_playbook_python }}"
aws_profile: opendata

postgres_host: "{{ postgres_conf.host }}"
postgres_admin_user: "{{ postgres_conf.admin_user }}"
postgres_admin_password: "{{ postgres_conf.admin_password }}"

postgres_users:
  - username: ckan_default
    password: "{{ secret.database_ckan_password }}"
  - username: datastore_default
    password: "{{ secret.database_ckan_datastore_password }}"
  - username: drupal8
    password: "{{ secret.database_drupal8_password }}"

ckan_postgres:
  users:
    ckan:
      username: ckan_default
      password: "{{ secret.database_ckan_password }}"
    ckan_datastore:
      username: datastore_default
      password: "{{ secret.database_ckan_datastore_password }}"
    drupal8:
      username: drupal8
      password: "{{ secret.database_drupal8_password }}"
  server:
    host: 127.0.0.1
  databases:
    ckan:
      name: ckan_default
      owner: ckan_default
    ckan_datastore:
      name: datastore_default
      owner: ckan_default
    drupal8:
      name: drupal8
      owner: drupal8