ckan_hostname: "{{ hostname }}"
ckan_secondary_hostname: "{{ secondary_hostname }}"
ckan_profiling_enabled: false
ckan_smtp_use_tls: True
ckan_smtp_username: "{{ secret.smtp_user }}"
ckan_smtp_password: "{{ secret.smtp_password }}"
ckan_smtp_server_domain: "email-smtp.eu-west-1.amazonaws.com"
ckan_enable_cloudstorage: True
ckan_site_protocol: https
ckan_extension_archiver_cache_protocol: https
ckan_cloudstorage_driver: "{{ AWS.region }}"
ckan_cloudstorage_bucket: "{{ AWS.ckan_s3_bucket }}"
ckan_cloudstorage_local_access: False
ckan_disqus_name: "{{ disqus_name }}"
ckan_postgres:
  users:
    ckan:
      username: ckan_default
      password: pass
    ckan_datastore:
      username: datastore_default
      password: pass
    drupal8:
      username: drupal8
      password: pass
  server:
    host: 127.0.0.1
  databases:
    ckan:
      name: ckan_default
      owner: ckan_default
    ckan_datastore:
      name: datastore_default
      owner: ckan_default
    drupal8:
      name: drupal8
      owner: drupal8