---

ckan_package: python-ckan_{{ ckan_version }}-precise_amd64.deb

harvester_user: "{{ www_user }}"
celery_user: "{{ www_user }}"

ckan_plugins_default: stats scheming_datasets scheming_groups scheming_organizations fluent
# order matters, when templates call super()
ckan_plugins: harvest ckan_harvester hri_harvester dcat dcat_rdf_harvester dcat_json_harvester dcat_json_interface spatial_metadata spatial_query csw_harvester drupal8 ytp_organizations ytp_request hierarchy_display ytp_theme report ytp_report ytp_drupal ytp_tasks ytp_dataset ytp_spatial ytp_user ytp_service datastore sixodp_showcase sixodp_showcasesubmit datapusher recline_grid_view recline_graph_view recline_map_view text_view image_view pdf_view geo_view geojson_view sixodp_harvester disqus reminder ytp_restrict_category_creation_and_updating archiver qa
ckan_aws_plugins: cloudstorage

ckan_extensions:
  - ckanext-drupal8
  - ckanext-ytp_drupal
  - ckanext-ytp_tasks
  - ckanext-ytp_request
  - ckanext-ytp_main
  - ckanext-hierarchy
  - ckanext-googleanalytics
  - ckanext-datarequests
  - ckanext-harvest
  - ckanext-report
  - ckanext-spatial
  - ckanext-dcat
  - ckanext-cloudstorage
  - ckanext-scheming
  - ckanext-fluent
  - ckanext-showcase
  - ckanext-sixodp_showcase
  - ckanext-sixodp_showcasesubmit
  - ckanext-geoview
  - ckanext-pdfview
  - ckanext-disqus
  - ckanext-reminder
  - ckanext-archiver
  - ckanext-qa


redis_harvest_database: 0
redis_celery_database: 1

supervisor_services:
  - ckan_gather_consumer
  - ckan_fetch_consumer
  - ckan-worker-bulk
  - ckan-worker-priority

# Override these on servers!
baker_session_secret: "9PBdkxokLGWW4M4jeTI25h+4t"
app_instance_uuid: "{dc6259b8-f112-4d23-8816-aadcede1895c}"

ckan_files_path: "{{ files_root }}/ckan"
ckan_max_resource_size: 5000


ckan_site_id: "default"

patches_cache_path: "{{ cache_path }}/patch"
ckan_source_path: "{{ virtual_environment }}/src/ckan"
spatial_source_path: "{{ virtual_environment }}/src/ckanext-spatial"

new_ckan_patches:
  - { file: "enable_multiple_image_uploads" }
  - { file: "remove-ckan-fontawesome" }
  - { file: "fix-flask-root-path" } # CKAN issue #4452

service_database_enabled: false
auto_author_enabled: true
