---

- name: Ensure local cache
  local_action: file state=directory path="{{ local_cache }}"
  become: false
  tags:
    - drupal
    - features

- name: Tar extracted features
  local_action: command tar -c --exclude=.git -f "{{ local_cache }}/{{ item }}.tar" {{ item }} chdir="{{ ytp_features_path }}"
  become: false
  with_items: "{{ extracted_features }}"
  tags:
    - drupal
    - features

- name: Prepare features install
  file: path="{{ features_module_path }}" state=directory
  tags:
  - drupal
  - features

- name: Copy and install extracted features
  unarchive: src="{{ local_cache }}/{{ item }}.tar" dest="{{ features_module_path }}"
  register: extracted_features_copy
  with_items: "{{ extracted_features }}"
  tags:
    - drupal
    - features

- name: Disable features
  command: drush dis -y "{{ item.item }}" chdir="{{drupal_root}}"
  when: extracted_features_copy|changed and item.changed
  with_items:
    - "{{extracted_features_copy.results}}"
  tags:
    - drupal
    - features

- name: Enable features
  command: drush en -y "{{ item.item }}" chdir="{{ drupal_root }}"
  when: extracted_features_copy|changed and item.changed
  with_items:
    - "{{extracted_features_copy.results}}"
  tags:
  - drupal
  - features
